theme: minima
title: Biblioteca Virtual Graciela Hierro
author: Adela H.R.
email: adelahernandezva@aragon.unam.mx
description: > # this means to ignore newlines until "baseurl:"
 Esta biblioteca virtual tiene como objetivo preservar la memoria de la biblioteca feminista de Graciela Hierro que ninguna institución quiso resguardar sus libros
 porque el tema de las mujeres, poco importa. 

# social links
twitter_username: Hermanita_ # DO NOT include the @ character, or else the build will fail!
github_username:  maria-adela-hernandez-reyes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
